[14.0][ADD] modules integración Mod322 con Prorata especial
oxigensalud/odoo-community-addons pull request #1
Opened 2023-11-20 08:58 UTC by etobella

Replaces https://github.com/oxigensalud/odoo-addons/pull/136

2023-11-21 12:09 UTC, eantones requested changes

2023-11-21 12:09 UTC, eantones commented on l10n_es_aeat_mod322_special_prorate/static/description/icon.png
Este logo debería cambiarse en todos los módulos de este PR

2023-11-22 15:40 UTC, etobella commented on l10n_es_aeat_mod322_special_prorate/static/description/icon.png
Toda la razón

2023-12-15 09:23 UTC, eantones approved these changes

2023-12-18 22:25 UTC, eantones requested changes
Also, please squash the following commits so that I can proceed with the merge:

-  [[FIX] adapt test-requirements](https://github.com/oxigensalud/odoo-community-addons/pull/1/commits/275d4450fa049746b946bb64e6afa8af8fe67fc0) and [fixup! [FIX] adapt test-requirements](https://github.com/oxigensalud/odoo-community-addons/pull/1/commits/52954c0af71fea2aeff3bb5d6c26c72f253ec5a6) 
- [[FIX] pylint: Adapt](https://github.com/oxigensalud/odoo-community-addons/pull/1/commits/f25d79593fed1cfc95ccf589aaeb07f6e70528bb) with each of the "[ADD]" commits

2023-12-18 22:25 UTC, eantones commented on l10n_es_aeat_mod322_special_prorate_regularization_capital_asset_legacy/__manifest__.py
>      "author": "NuoBiT Solutions, S.L.",
Change this please

2023-12-19 10:04 UTC, etobella commented on l10n_es_aeat_mod322_special_prorate_regularization_capital_asset_legacy/__manifest__.py
>      "author": "NuoBiT Solutions, S.L.",
Done!

2023-12-19 20:42 UTC, eantones approved these changes

2023-12-19 20:42 UTC, merged